### ISSUE TITLE
Opam-switch output uses short git commit

### ISSUE THREAD

**Issue by reynir** [roburio/orb#8]
I noticed in a build that the commit referenced was using the short form: https://builds.robur.coop/job/builder-web/build/9991177a-01a2-435d-be9d-eb8c359d6c98/f/opam-switch

    src: "git+https://git.robur.io/robur/builder-web.git#ac8c31f2"

I think we should be using the full form as the commit may become ambiguous in the future. This would be a problem for reproducibility. I have not investigated the source of this.

**Comment by hannesm** [comment]
The origin is the "opam switch --freeze" which uses OpamGit.revision (in https://github.com/ocaml/opam/blob/2.1.3/src/repository/opamGit.ml#L150-L163), and indeed maybe it is suitable to remove the `String.sub` from there...

**Comment by hannesm** [comment]
If I understand correctly, https://github.com/ocaml/opam/pull/5342 solves the issue described above. But there doesn't seem to be much progress in that issue (it is "approved", but also "waiting for review").

**Comment by hannesm** [comment]
The opam PR has been merged and will appear in 2.2.0 AFAICT. I'll close this issue since that's all we can do in here...
